### ISSUE TITLE
Performance issue with monsters

### ISSUE THREAD

**Issue by TeemuKoivisto** [emlai/wge3#29]
I'm sure this is a well known bug but I feel it would be best to put it here so it's officially acknowledged. For example in the map creatively named "2" when you move player into bottom-left corner and the creeps start to gang up on you the game slows down immensely, probably because some of those creeps AIs are doing some heavy calculation. I don't know how the bug could be fixed but I think it's a huge issue that really affects the game, making it at times unplayable. Solving this issue would make this game even remotely resemble a working prototype.

**Comment by emlai** [comment]
We have done some improvements regarding this in the [`performance` branch](https://github.com/emlai/wge3/tree/performance). Can you reproduce this issue there?

**Comment by emlai** [comment]
Should be fixed by #30, at least in my testing.
